version: '3.4'

services:
  backend:
    image: backend
    build:
      context: back_end
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3333:3333
