version: "3"

services:
  postgres:
    image: "bitnami/postgresql"
    container_name: database_amalteia
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=amalteia
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - app-net
  app:
    container_name: amalteia
    build: .
    ports:
      - 3333:3333
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres

networks:
  app-net:
    driver: bridge

volumes:
  postgresql_data:
    driver: local